#!/usr/bin/env bash
# Code that automates moving a file to the remote server
if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# $4 path to ssh key, $2 ip address, $3 username, $1 path to the local file
	scp -i "$4" -o StrictHostKeyChecking=yes "$1" "$3@$2":~/
fi

