#!/usr/bin/env bash
# code that automatically installs "engine x" and inserts a string in the site
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo rm /var/www/html/index.nginx-debian.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
